<?php

declare(strict_types=1);

/*
 * -----------------------------------------------------------
 * Copyright 2002-2019 Adobe (http://www.adobe.com/).
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the
 * following conditions are met:
 *
 * Redistributions of source code must retain the above
 * copyright notice, this list of conditions and the following
 * disclaimer.
 *
 * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following
 * disclaimer in the documentation and/or other materials
 * provided with the distribution.
 *
 * Neither the name of Adobe nor the names of its contributors
 * may be used to endorse or promote products derived from this
 * software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
 * CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * -----------------------------------------------------------
 * Name:          ITC Zapf Dingbats Glyph List
 * Table version: 2.0
 * Date:          September 20, 2002
 * URL:           https://github.com/adobe-type-tools/agl-aglfn
 *
 * Format: two semicolon-delimited fields:
 *   (1) glyph name--upper/lowercase letters and digits
 *   (2) Unicode scalar value--four uppercase hexadecimal digits
 *
 */

// Generated by tools/generate-glyph-lists.php; do not edit.
// Source: adobe-type-tools/agl-aglfn at 4036a9ca80a62f64f9de4f7321a9a045ad0ecfd6.

return [
    'a100' => "\u{275E}",
    'a101' => "\u{2761}",
    'a102' => "\u{2762}",
    'a103' => "\u{2763}",
    'a104' => "\u{2764}",
    'a105' => "\u{2710}",
    'a106' => "\u{2765}",
    'a107' => "\u{2766}",
    'a108' => "\u{2767}",
    'a109' => "\u{2660}",
    'a10' => "\u{2721}",
    'a110' => "\u{2665}",
    'a111' => "\u{2666}",
    'a112' => "\u{2663}",
    'a117' => "\u{2709}",
    'a118' => "\u{2708}",
    'a119' => "\u{2707}",
    'a11' => "\u{261B}",
    'a120' => "\u{2460}",
    'a121' => "\u{2461}",
    'a122' => "\u{2462}",
    'a123' => "\u{2463}",
    'a124' => "\u{2464}",
    'a125' => "\u{2465}",
    'a126' => "\u{2466}",
    'a127' => "\u{2467}",
    'a128' => "\u{2468}",
    'a129' => "\u{2469}",
    'a12' => "\u{261E}",
    'a130' => "\u{2776}",
    'a131' => "\u{2777}",
    'a132' => "\u{2778}",
    'a133' => "\u{2779}",
    'a134' => "\u{277A}",
    'a135' => "\u{277B}",
    'a136' => "\u{277C}",
    'a137' => "\u{277D}",
    'a138' => "\u{277E}",
    'a139' => "\u{277F}",
    'a13' => "\u{270C}",
    'a140' => "\u{2780}",
    'a141' => "\u{2781}",
    'a142' => "\u{2782}",
    'a143' => "\u{2783}",
    'a144' => "\u{2784}",
    'a145' => "\u{2785}",
    'a146' => "\u{2786}",
    'a147' => "\u{2787}",
    'a148' => "\u{2788}",
    'a149' => "\u{2789}",
    'a14' => "\u{270D}",
    'a150' => "\u{278A}",
    'a151' => "\u{278B}",
    'a152' => "\u{278C}",
    'a153' => "\u{278D}",
    'a154' => "\u{278E}",
    'a155' => "\u{278F}",
    'a156' => "\u{2790}",
    'a157' => "\u{2791}",
    'a158' => "\u{2792}",
    'a159' => "\u{2793}",
    'a15' => "\u{270E}",
    'a160' => "\u{2794}",
    'a161' => "\u{2192}",
    'a162' => "\u{27A3}",
    'a163' => "\u{2194}",
    'a164' => "\u{2195}",
    'a165' => "\u{2799}",
    'a166' => "\u{279B}",
    'a167' => "\u{279C}",
    'a168' => "\u{279D}",
    'a169' => "\u{279E}",
    'a16' => "\u{270F}",
    'a170' => "\u{279F}",
    'a171' => "\u{27A0}",
    'a172' => "\u{27A1}",
    'a173' => "\u{27A2}",
    'a174' => "\u{27A4}",
    'a175' => "\u{27A5}",
    'a176' => "\u{27A6}",
    'a177' => "\u{27A7}",
    'a178' => "\u{27A8}",
    'a179' => "\u{27A9}",
    'a17' => "\u{2711}",
    'a180' => "\u{27AB}",
    'a181' => "\u{27AD}",
    'a182' => "\u{27AF}",
    'a183' => "\u{27B2}",
    'a184' => "\u{27B3}",
    'a185' => "\u{27B5}",
    'a186' => "\u{27B8}",
    'a187' => "\u{27BA}",
    'a188' => "\u{27BB}",
    'a189' => "\u{27BC}",
    'a18' => "\u{2712}",
    'a190' => "\u{27BD}",
    'a191' => "\u{27BE}",
    'a192' => "\u{279A}",
    'a193' => "\u{27AA}",
    'a194' => "\u{27B6}",
    'a195' => "\u{27B9}",
    'a196' => "\u{2798}",
    'a197' => "\u{27B4}",
    'a198' => "\u{27B7}",
    'a199' => "\u{27AC}",
    'a19' => "\u{2713}",
    'a1' => "\u{2701}",
    'a200' => "\u{27AE}",
    'a201' => "\u{27B1}",
    'a202' => "\u{2703}",
    'a203' => "\u{2750}",
    'a204' => "\u{2752}",
    'a205' => "\u{276E}",
    'a206' => "\u{2770}",
    'a20' => "\u{2714}",
    'a21' => "\u{2715}",
    'a22' => "\u{2716}",
    'a23' => "\u{2717}",
    'a24' => "\u{2718}",
    'a25' => "\u{2719}",
    'a26' => "\u{271A}",
    'a27' => "\u{271B}",
    'a28' => "\u{271C}",
    'a29' => "\u{2722}",
    'a2' => "\u{2702}",
    'a30' => "\u{2723}",
    'a31' => "\u{2724}",
    'a32' => "\u{2725}",
    'a33' => "\u{2726}",
    'a34' => "\u{2727}",
    'a35' => "\u{2605}",
    'a36' => "\u{2729}",
    'a37' => "\u{272A}",
    'a38' => "\u{272B}",
    'a39' => "\u{272C}",
    'a3' => "\u{2704}",
    'a40' => "\u{272D}",
    'a41' => "\u{272E}",
    'a42' => "\u{272F}",
    'a43' => "\u{2730}",
    'a44' => "\u{2731}",
    'a45' => "\u{2732}",
    'a46' => "\u{2733}",
    'a47' => "\u{2734}",
    'a48' => "\u{2735}",
    'a49' => "\u{2736}",
    'a4' => "\u{260E}",
    'a50' => "\u{2737}",
    'a51' => "\u{2738}",
    'a52' => "\u{2739}",
    'a53' => "\u{273A}",
    'a54' => "\u{273B}",
    'a55' => "\u{273C}",
    'a56' => "\u{273D}",
    'a57' => "\u{273E}",
    'a58' => "\u{273F}",
    'a59' => "\u{2740}",
    'a5' => "\u{2706}",
    'a60' => "\u{2741}",
    'a61' => "\u{2742}",
    'a62' => "\u{2743}",
    'a63' => "\u{2744}",
    'a64' => "\u{2745}",
    'a65' => "\u{2746}",
    'a66' => "\u{2747}",
    'a67' => "\u{2748}",
    'a68' => "\u{2749}",
    'a69' => "\u{274A}",
    'a6' => "\u{271D}",
    'a70' => "\u{274B}",
    'a71' => "\u{25CF}",
    'a72' => "\u{274D}",
    'a73' => "\u{25A0}",
    'a74' => "\u{274F}",
    'a75' => "\u{2751}",
    'a76' => "\u{25B2}",
    'a77' => "\u{25BC}",
    'a78' => "\u{25C6}",
    'a79' => "\u{2756}",
    'a7' => "\u{271E}",
    'a81' => "\u{25D7}",
    'a82' => "\u{2758}",
    'a83' => "\u{2759}",
    'a84' => "\u{275A}",
    'a85' => "\u{276F}",
    'a86' => "\u{2771}",
    'a87' => "\u{2772}",
    'a88' => "\u{2773}",
    'a89' => "\u{2768}",
    'a8' => "\u{271F}",
    'a90' => "\u{2769}",
    'a91' => "\u{276C}",
    'a92' => "\u{276D}",
    'a93' => "\u{276A}",
    'a94' => "\u{276B}",
    'a95' => "\u{2774}",
    'a96' => "\u{2775}",
    'a97' => "\u{275B}",
    'a98' => "\u{275C}",
    'a99' => "\u{275D}",
    'a9' => "\u{2720}",
];
