<?php

declare(strict_types=1);

/*
 * This file is part of the ALTO library.
 *
 * © 2026-present Simon André
 *
 * For full copyright and license information, please see
 * the LICENSE file distributed with this source code.
 */

// Run from any directory: php tools/generate-glyph-lists.php
// The original Adobe files are deliberately retained, including their license.
foreach (['glyphlist', 'zapfdingbats'] as $name) {
    $path = __DIR__ . '/../resources/glyph-list/' . $name;
    $source = file($path . '.txt', FILE_IGNORE_NEW_LINES);

    if (false === $source) {
        throw new RuntimeException('Cannot read ' . $path . '.txt.');
    }

    $header = [];
    $entries = [];

    foreach ($source as $line) {
        if (str_starts_with($line, '#')) {
            if ([] === $entries) {
                $header[] = ' *' . substr($line, 1);
            }

            continue;
        }

        if ('' === $line) {
            continue;
        }

        if (1 !== preg_match('/\A([A-Za-z0-9]+);([0-9A-F]{4}(?: [0-9A-F]{4})*)\z/', $line, $matches)) {
            throw new RuntimeException('Invalid glyph-list entry: ' . $line);
        }

        if (isset($entries[$matches[1]])) {
            throw new RuntimeException('Duplicate glyph-list name: ' . $matches[1]);
        }

        $value = '';

        foreach (explode(' ', $matches[2]) as $hex) {
            $codepoint = hexdec($hex);

            if ($codepoint >= 0xD800 && $codepoint <= 0xDFFF) {
                throw new RuntimeException('Surrogate in glyph-list entry: ' . $line);
            }

            $value .= '\\u{' . $hex . '}';
        }

        $entries[$matches[1]] = "    '" . $matches[1] . "' => \"" . $value . "\",";
    }

    $output = "<?php\n\ndeclare(strict_types=1);\n\n/*\n" . implode("\n", $header) . "\n */\n\n"
        . "// Generated by tools/generate-glyph-lists.php; do not edit.\n"
        . "// Source: adobe-type-tools/agl-aglfn at 4036a9ca80a62f64f9de4f7321a9a045ad0ecfd6.\n\n"
        . "return [\n" . implode("\n", $entries) . "\n];\n";

    if (false === file_put_contents($path . '.php', $output)) {
        throw new RuntimeException('Cannot write ' . $path . '.php.');
    }
}
